koikiss-dev/jimov_api

package-lock.json
package.json
src/scraper/sites/anime/animeflv/AnimeFlv.ts
src/types/anime.d.ts
src/types/schemaProviders.ts
tsconfig.json

Animeflv provider with typescript

---

src/scraper/sites/anime/gogoanime/Gogoanime.ts

BRO YA TERMINE LA FUNCIONALIDAD DEL OTAKUTV Y TODO MUY CHILL ESTA FUNCIONANDO ACANASLDKJA
POST: ES UYNA PRUEBA NO ME CANCELEN

refactor: im doing an example about pull request

---

src/scraper/sites/anime/animeflv/AnimeFlv.ts

test, new error message animeflv anime

fix: error message

---

src/types/manga.ts

Creating the manga interface, it has required and optional values and will work for both NSFW and non-NSFW content

feat(manga interface): creating the manga interface, it has required and optional values and will work for both NSFW and non-NSFW content

---

src/types/manga.ts

This commit allow to add the manga volumes.

refactor: add volumes property

---

src/scraper/sites/anime/animelatinohd/AnimeLatinoHD.ts
src/test/Animelatinohd.spec.ts

+ Add jest test (Animelatinohd)
* Fix error url list episodes
* Fix error search Results

Fix url error and search (add jest test)

---

src/scraper/sites/manga/nhentai/Nhentai.ts
src/scraper/sites/manga/nhentai/assets/getFilterByPage.ts
src/test/Nhentai.spec.ts

Okay that changes is i add filter by search from nhentai, it get information type mangaResults:
it gets
id from manga
title from manga
url adapted to route API
thumbnail as coverImg

feat(filter): i add filter nhentai!!

---

src/scraper/sites/manga/MangaBuddy/MangaBuddy.ts
src/types/date.ts

Modify the date.ts so that the ICalendar interface accepts both string and number and update mangabuddy.

MangaBuddy and date interface

---

src/index.ts
src/routes/v1/manga/nhentai/NhentaiRoutes.ts
src/scraper/sites/manga/nhentai/Nhentai.ts
src/test/Nhentai.spec.ts

nhentai done, with other changes and update branch

Feature nhentai

---

src/scraper/sites/manga/nhentai/Nhentai.ts

fix when calling the nhentai api, it's happen because consulting by page with a -3

fix: i fixed a bug that dont get anything

---

src/index.ts
src/routes/v1/manga/inmanga/InmangaRoutes.ts
src/scraper/sites/manga/inmanga/Inmanga.ts
src/test/Inmanga.spec.ts

add manga(inmanga) and fix index.ts

---

src/types/manga.ts

I made this change to storage volume pages (images) into `IMangaVolume.images`, something like `IMangaChapter.images`.

chore: images property added to IMangaVolume and MangaVolume

---

src/scraper/sites/manga/MangaReader/MangaReader.ts

fix: puppeteer

---

tsconfig.json

fixed the problem related with routes

fix: fixed routes in tsconfig

---

src/scraper/sites/manga/comick/Comick.ts

I don't know if this happened to more providers but it could still be a change to the page or cloudflare but that's it.

fix request([api]comick[GET,POST) need user-agent and cookies

---

tsconfig.json

This commit fixes the error 'Cannot find module '@...' or its corresponding type declarations.' when you try to import a file and the CI workflow is executed.

Path annotation

---

.eslintrc.json

feat: linter configuration

---

package.json
src/routes/v1/doramas/dramanice/DramaniceRoutes.ts
src/scraper/sites/anime/animeflv/AnimeFlv.ts
src/scraper/sites/doramas/dramanice/Dramanice.ts
src/types/utils.ts
tsconfig.json

Fixed AnimeFLV Episode Number/source file problem
source file:
Episode Number:
view error [jimov-api.vercel.app/anime/flv/episode/zom-100-zombie-ni-naru-made-ni-shitai-100-no-koto-7](https://jimov-api.vercel.app/anime/flv/episode/zom-100-zombie-ni-naru-made-ni-shitai-100-no-koto-7)

fixed: AnimeFLV

---

src/scraper/sites/manga/manganelo/ManganatoManagerUtils.ts
src/scraper/sites/manga/manganelo/ManganatoTypes.ts
src/scraper/sites/manga/manganelo/managers/ManganatoURLManager.ts

- feat(types): ManganatoFilterURLParams
- fix(manganato): error when genre is not provided
- fix(ManganatoManager): singleton implementation

fix(ManganeloFilter): error when genres parameter is not provided

---

src/routes/v1/manga/manganelo/ManganeloRoutes.ts
src/routes/v1/manga/mangareader/MangaReaderRoutes.ts
src/scraper/sites/manga/MangaReader/MangaReader.ts
src/scraper/sites/manga/manganelo/Manganelo.ts
src/test/MangaReader.spec.ts
src/test/Manganelo.spec.ts

- fix(manganelo): class implementation and tests
- fix(mangareader): class implementation and tests

fix(providers): migrating the class implementation of MangaReader and Manganelo
